const sampleAssets = [
  {
    serialNo: "SN10001",
    location: "Mumbai Office",
    category: "Laptop",
    manufacturer: "Dell",
    model: "Latitude 7420",
    modelNo: "DLT7420",
    employeeCode: "EMP001",
    employeeName: "Amit Sharma",
    department: "IT",
    ram: "16GB",
    hdd: "512GB SSD",
    processor: "Intel i7",
    keyboard: "Wireless",
    mouse: "Wireless",
    ip: "192.168.1.101",
    monitor: "14-inch",
    os: "Windows 11",
    antivirus: "McAfee",
    warrenty: "3 Years",
    office: "MS Office 365",
  },
  {
    serialNo: "SN10002",
    location: "Delhi Office",
    category: "Desktop",
    manufacturer: "HP",
    model: "EliteDesk 800",
    modelNo: "HP800G6",
    employeeCode: "EMP002",
    employeeName: "Priya Verma",
    department: "Finance",
    ram: "8GB",
    hdd: "1TB HDD",
    processor: "Intel i5",
    keyboard: "Wired",
    mouse: "Wired",
    ip: "192.168.1.102",
    monitor: "24-inch",
    os: "Windows 10",
    antivirus: "Norton",
    warrenty: "2 Years",
    office: "MS Office 2019",
  },
  {
    serialNo: "SN10003",
    location: "Bangalore Office",
    category: "Laptop",
    manufacturer: "Lenovo",
    model: "ThinkPad X1",
    modelNo: "TPX1G9",
    employeeCode: "EMP003",
    employeeName: "Rahul Mehta",
    department: "HR",
    ram: "32GB",
    hdd: "1TB SSD",
    processor: "Intel i9",
    keyboard: "Backlit",
    mouse: "Wireless",
    ip: "192.168.1.103",
    monitor: "15.6-inch",
    os: "Windows 11",
    antivirus: "Kaspersky",
    warrenty: "4 Years",
    office: "MS Office 365",
  },
  {
    serialNo: "SN10004",
    location: "Chennai Office",
    category: "Laptop",
    manufacturer: "Apple",
    model: "MacBook Pro",
    modelNo: "MBP16",
    employeeCode: "EMP004",
    employeeName: "Sneha Reddy",
    department: "Marketing",
    ram: "16GB",
    hdd: "512GB SSD",
    processor: "M1",
    keyboard: "Backlit",
    mouse: "Trackpad",
    ip: "192.168.1.104",
    monitor: "16-inch",
    os: "macOS",
    antivirus: "None",
    warrenty: "3 Years",
    office: "MS Office 365",
  },
  {
    serialNo: "SN10005",
    location: "Hyderabad Office",
    category: "Desktop",
    manufacturer: "Acer",
    model: "Veriton X",
    modelNo: "VX2660G",
    employeeCode: "EMP005",
    employeeName: "Kunal Das",
    department: "Operations",
    ram: "8GB",
    hdd: "1TB HDD",
    processor: "Intel i3",
    keyboard: "Wired",
    mouse: "Wired",
    ip: "192.168.1.105",
    monitor: "22-inch",
    os: "Windows 10",
    antivirus: "Avast",
    warrenty: "2 Years",
    office: "MS Office 2016",
  },
  {
    serialNo: "SN10006",
    location: "Bangalore Office",
    category: "Laptop",
    manufacturer: "Lenovo",
    model: "ThinkPad X1",
    modelNo: "LE5869",
    employeeCode: "EMP006",
    employeeName: "Jeffery Gray",
    department: "Marketing",
    ram: "64GB",
    hdd: "512GB SSD",
    processor: "Intel i5",
    keyboard: "Wired",
    mouse: "Wireless",
    ip: "192.168.1.106",
    monitor: "15.6-inch",
    os: "Windows 10",
    antivirus: "Windows Defender",
    warrenty: "5 Years",
    office: "MS Office 365",
  },
  {
    serialNo: "SN123456",
    location: "Mumbai Office",
    category: "Laptop",
    manufacturer: "Dell",
    model: "Latitude 7420",
    modelNo: "DLT7420",
    employeeCode: "EMP001",
    employeeName: "Amit Sharma",
    department: "IT",
    ram: "16GB",
    hdd: "512GB SSD",
    processor: "Intel i7",
    keyboard: "Wireless",
    mouse: "Wireless",
    ip: "192.168.1.101",
    monitor: "14-inch",
    os: "Windows 11",
    antivirus: "McAfee",
    warrenty: "3 Years",
    office: "MS Office 365",
  },
  {
    serialNo: "SN654321",
    location: "Delhi Office",
    category: "Desktop",
    manufacturer: "HP",
    model: "EliteDesk 800",
    modelNo: "HP800G6",
    employeeCode: "EMP002",
    employeeName: "Priya Verma",
    department: "Finance",
    ram: "8GB",
    hdd: "1TB HDD",
    processor: "Intel i5",
    keyboard: "Wired",
    mouse: "Wired",
    ip: "192.168.1.102",
    monitor: "24-inch",
    os: "Windows 10",
    antivirus: "Norton",
    warrenty: "2 Years",
    office: "MS Office 2019",
  },
  {
    serialNo: "SN789012",
    location: "Bangalore Office",
    category: "Laptop",
    manufacturer: "Lenovo",
    model: "ThinkPad X1",
    modelNo: "TPX1G9",
    employeeCode: "EMP003",
    employeeName: "Rahul Mehta",
    department: "HR",
    ram: "32GB",
    hdd: "1TB SSD",
    processor: "Intel i9",
    keyboard: "Backlit",
    mouse: "Wireless",
    ip: "192.168.1.103",
    monitor: "15.6-inch",
    os: "Windows 11",
    antivirus: "Kaspersky",
    warrenty: "4 Years",
    office: "MS Office 365",
  },
];

module.exports = { data: sampleAssets };
