const Joi = require("joi");

module.exports.assetSchema = Joi.object({
  //   asset: Joi.object().required,
  serialNo: Joi.string(),
  location: Joi.string(),
  category: Joi.string(),
  manufacturer: Joi.string(),
  model: Joi.string(),
  modelNo: Joi.string(),
  employeeCode: Joi.string(),
  employeeName: Joi.string(),
  department: Joi.string(),
  ram: Joi.string(),
  hdd: Joi.string(),
  processor: Joi.string(),
  keyboard: Joi.string(),
  mouse: Joi.string(),
  ip: Joi.string(),
  monitor: Joi.string(),
  os: Joi.string(),
  antivirus: Joi.string(),
  warrenty: Joi.string(),
  office: Joi.string(),
});

module.exports.callLogSchema = Joi.object({
  callLog: Joi.object({
    plant: Joi.string().required(),
    department: Joi.string().required(),
    employeeCode: Joi.string().required(),
    employeeName: Joi.string().required(),
    category: Joi.string().required(),
    serialNumber: Joi.string().required(),
    callNumber: Joi.number().required(),
    problemDescription: Joi.string().required(),
    reportingDate: Joi.date().required(),
    attendingDate: Joi.date().required(),
    attendedBy: Joi.string().required(),
    solutionDate: Joi.date().required(),
    remarks: Joi.string().required(),
    sendDate: Joi.date().required(),
    gatePassNumber: Joi.number().required(),
    receiveDate: Joi.date().required(),
    challanNumber: Joi.number().required(),
    serviceProviderName: Joi.string().required(),
  }).required(),
});
